### ISSUE TITLE
Availbility through package manager

### ISSUE THREAD

**Issue by lguariento** [eXist-db/existdb-login#2]
I love the idea behind this! Is there any way it can be available to be installed via the package manager?

**Comment by JoernT** [comment]
not sure i understand. Do you mean to be installable from public repository? Of course you can already build it with ant and install the xar via package manager

**Comment by lguariento** [comment]
Yes, I meant public repository, showing up in the list of available application in the package manager. Anyway, just a thought!

**Comment by JoernT** [comment]
ah, ok - just uploaded to public repo
